[[language]]
name = "elixir"
scope = "source.elixir"
file-types = ["ex", "exs", "hex"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-servers = ["elixir-ls"]
